### ISSUE TITLE
Upload raw data file to Github

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/DEI-Framework#13]
159 survey responses collected between October 7, 2020 and December 2, 2020 via the partner survey in partnership with Amplify and the Equality Committee of Salesforce.org Partner Advisory Group.

**Comment by charise** [comment]
[Diversity, Equity & Inclusion Survey for Salesforce.org Consulting Partners (Responses).xlsx](https://github.com/SFDO-Community-Sprints/DEI-Framework/files/5705441/Diversity.Equity.Inclusion.Survey.for.Salesforce.org.Consulting.Partners.Responses.xlsx)

**Comment by spilzer** [comment]
Uploaded file here: https://github.com/SFDO-Community-Sprints/DEI-Framework/blob/master/January%202021%20DEI%20Partner%20Survey%20Results.xlsx

**Comment by cboyd1914** [comment]
Uploaded File 

[2021-VSP-AMER.xlsx](https://github.com/SFDO-Community-Sprints/DEI-Framework/files/8633093/2021-VSP-AMER.xlsx)
