### ISSUE TITLE
Document tool and process used for first survey analysis

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/DEI-Framework#4]
Michael - any chance you could shed some light on this or point us to the right person who has this info? Before I re-invent the wheel: (1) what tool did your team use to prep and analyze the data? Excel, PowerBI? (2) where are the files with the raw data stored? I'd like to post them to github. -Charise

**Comment by mkolodner** [comment]
I would have guessed that Brittany had that data. I think that responses are in this sheet: https://docs.google.com/spreadsheets/d/1FXNvMp5onUqxNxjXFj5bD-AcMtN-7wmmVvaXnwLMO2Y/edit#gid=1748533587
But the actual data analysis was not done by me.

**Comment by mkolodner** [comment]
Oooh! I find this sheet (created by Brittany): https://docs.google.com/spreadsheets/d/1axnclYjiCkxLCrg7QUCPKH4i0MZMhvjPsImRogzF1Ho/edit#gid=1748533587

**Comment by ebloks01** [comment]
Brittany brought in the raw data and then I and a friend who's a financial analysis pulled the data into excel and created different graphs. Super simple process.
