### ISSUE TITLE
Upload raw data from Sep Sprint dei survey

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/DEI-Framework#5]

**Comment by charise** [comment]
Thanks Akash!

**Comment by charise** [comment]
@aka5h4u Are you planning to remove personal identifying info from the raw data and repost? I lost track of where that left off.

**Comment by aka5h4u** [comment]
Hi @charise, I've removed the column number 13 which discloses the person's identity who's filling out the survey. It's raw data and Anonymous, therefore I named the file : (Anonymous) Sept '20-Post Sprint DEI Participant Survey
