### ISSUE TITLE
Confirm all mini sprinters listed as team members

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/DEI-Framework#8]
Karen - would you mind checking to see if all folks from the last mini sprint are listed as team members at the bottom of the README? I noticed I missed Qurat so I may have missed others. https://github.com/SFDO-Community-Sprints/DEI-Framework

**Comment by karenfitton** [comment]
I wasn't in the last mini-sprint so I'm not sure who all participated. I did update it though to add folks that were at the table in Philly.

**Comment by karenfitton** [comment]
@coriobriensfdo I know we should be tracking it but do you have a list of who participated in the mini-Sprint in October? Going forward, we will be better at updating the list.

**Comment by coriobriensfdo** [comment]
@charise Everyone who checked in is on the [artifact doc](https://salesforce.quip.com/rdasA2YVPR1E) :)

**Comment by karenfitton** [comment]
I'll update our list. Thanks Cori!

**Comment by charise** [comment]
Thanks for doing this @karenfitton!
