### ISSUE TITLE
Update About section

### ISSUE THREAD

**Issue by charise** [SFDO-Community-Sprints/DEI-Framework#9]
Cori - I can't figure out how to edit the 'About' section of the repo. It currently reads "Open Source Community Sprint project focused on The DEI project is focused on increasing the diversity, equality and inclusion at the Sprints." would you be able to change it to "Open Source Community Sprint project focused on increasing the diversity, equality and inclusion at the Sprints and creating a framework for the nonprofit Salesforce ecosystem." Thanks! CVL

**Comment by coriobriensfdo** [comment]
Done! I think you need to be an admin of the Org to edit that, but I can manage that going forward if you create an Issue for me like this :)
